---
# tasks file for ansible-network-tools
- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
